-- AlterEnum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BOMBERO_HONORARIO';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BOMBERO_INICIAL';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BOMBERO_PROFESIONAL';
