import { IncidentTimelineKind } from '@prisma/client';

export const INCIDENT_TIMELINE_LABELS: Record<IncidentTimelineKind, string> = {
  AVISO: 'Aviso / Llamada',
  CONFIRMACION: 'Confirmación del aviso',
  DIRECCION_ACTUALIZADA: 'Dirección actualizada',
  CAMBIO_CLAVE: 'Cambio de clave',
  SEGUNDA_ALARMA: '2ª alarma',
  TERCERA_ALARMA: '3ª alarma',
  DESPACHO: 'Despacho',
  EN_CAMINO: 'En camino',
  ACCIDENTE_RUTA: 'Accidente en ruta',
  UNIDAD_AVERIADA: 'Unidad averiada',
  EN_LUGAR: 'En el lugar',
  RECONOCIMIENTO: 'Reconocimiento',
  PUESTO_MANDO: 'Puesto de mando',
  PERIMETRO: 'Perímetro de seguridad',
  APOYO: 'Apoyo compañías',
  REFUERZO: 'Refuerzo solicitado',
  SAMU: 'SAMU / Ambulancia',
  CARABINEROS: 'Carabineros',
  PDI: 'PDI',
  CONAF: 'CONAF',
  SENAPRED: 'SENAPRED',
  MUNICIPALIDAD: 'Municipalidad',
  ELECTRICIDAD: 'Empresa eléctrica',
  AGUAS: 'Empresa de agua',
  GRUA: 'Grúa',
  HIDRANTE: 'Hidrante / Agua',
  AGUA_INSUFICIENTE: 'Agua insuficiente',
  VENTILACION: 'Ventilación',
  ATAQUE_INTERIOR: 'Ataque interior',
  ATAQUE_EXTERIOR: 'Ataque exterior',
  BUSQUEDA: 'Búsqueda',
  RESCATE: 'Rescate',
  EVACUACION: 'Evacuación',
  CORTE_LUZ: 'Corte de luz',
  CORTE_GAS: 'Corte de gas',
  CIERRE_VIA: 'Cierre de vía',
  HAZMAT: 'HazMat / sustancias',
  EXPLOSION: 'Explosión',
  COLAPSO: 'Colapso estructural',
  PROPAGACION: 'Propagación',
  REBROTE: 'Rebrote',
  AMAGO: 'Amago',
  PERSONAS: 'Personas involucradas',
  PERSONA_ATRAPADA: 'Persona atrapada',
  MENOR_INVOLUCRADO: 'Menor involucrado',
  VICTIMA: 'Víctima civil',
  VICTIMA_FATAL: 'Víctima fatal',
  TRASLADO: 'Traslado a hospital',
  INTOXICACION: 'Intoxicación',
  QUEMADURA: 'Quemadura',
  RCP: 'RCP',
  PRIMEROS_AUXILIOS: 'Primeros auxilios',
  BOMBERO_HERIDO: 'Bombero herido',
  BOMBERO_ATRAPADO: 'Bombero atrapado',
  MAYDAY: 'MAYDAY',
  CONTROLADO: 'Controlado',
  EXTINTO: 'Extinto',
  FALSA_ALARMA: 'Falsa alarma',
  VIGILANCIA: 'Vigilancia / sobreestadía',
  ENTREGA_LUGAR: 'Entrega del lugar',
  REGRESO: 'Regreso a cuartel',
  EN_CUARTEL: 'En cuartel',
  DISPONIBLE: 'Unidades disponibles',
  COMENTARIO: 'Comentario',
};
